name: JSHint
on:
  push:
    branches:
      - main
jobs:
  jshint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install JSHint
        run: npm install -g jshint
      - name: Run on repo
        run: jshint src/ > jshint-report.txt
      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: jshint-report.txt
